Larpon/QtFirebase

README.md, fake/src/qtfirebaseremoteconfig.h, qtfirebase.pri, qtfirebase_dummy.pri, qtfirebase_register.h, qtfirebase_target.pri, src/qtfirebase.cpp, src/qtfirebase_plugin.cpp, src/qtfirebaseremoteconfig.cpp, src/qtfirebaseremoteconfig.h
Implement basic support for Firebase Remote Config 
(not tested for ios, unfortunately I have no environment to test, so linking stage may fail, probably may require project file libs section to fix). 
Example of how to use in QML code added to remote config class header file.
=> Implement basic support for Firebase Remote Config

fake/src/qtfirebaseremoteconfig.h, src/qtfirebaseremoteconfig.cpp, src/qtfirebaseremoteconfig.h
Update RemoteConfig class to fit QML better. Added "parameters" and "cacheExpirationTime" variable in milliseconds. Removed "loaded" variables and signals. Updated example code in the class header.
=> Update remote config wrapper API to fit QML code better

fake/src/qtfirebaseadmob.h, src/qtfirebaseadmob.cpp, src/qtfirebaseadmob.h, src/qtfirebaseremoteconfig.cpp
Similar to interstitial but also contains time on the Ad,  when time is out user can close the banner and get reward (is a value of float type, can be coins/starts/points in your game). 
I didn't get any docs on google about reinitializing rewarded Ad on ios as it was mentioned regarding interstitial. So it could be needed or not I don't know, disabled for now (have no ability to check on ios)
=> Added rewarded admob banner

fake/src/qtfirebaseadmob.h, fake/src/qtfirebaseremoteconfig.h, src/qtfirebaseadmob.cpp, src/qtfirebaseadmob.h, src/qtfirebaseanalytics.cpp
- [Firebase Official doc for NativeExpressAd](https://firebase.google.com/docs/admob/cpp/native-express)
- Add `QtFirebaseNativeExpressAd` implementation, both in target.pri and fake.pri.
- Fix some compilation warnings
=> Add support to admob::NativeExpress type; fix some compilation warnings 

fake/src/qtfirebaseadmob.h, src/qtfirebaseadmob.cpp, src/qtfirebaseadmob.h
Consider the following situation:
1. A App has several screens, each screen has different type Ads, one is Banner, another is NativeExpress, then a Interstitial between screen switching.
1. Currently `QtFirebaseAdMobBanner` and `QtFirebaseAdMobNativeExressAd`  connect there slots to `QGuiApplication::applicationStateChanged` in their constructor, which will lead to
- Application cannot control when to display what kind of Ads by their logic. Every time switch the app to background and then foreground, or unlock the screen will make the Banner and NativeExpress Ads displayed again.
- Closing an interstitial Ad also will also trigger the `QGuiApplication::applicationStateChanged` too.
1. So I suggest let app control the behavior on how to react to the …
=> Let application react to `QGuiApplication::applicationStateChanged` signal

src/qtfirebaseremoteconfig.cpp, src/qtfirebaseremoteconfig.h
Delay init of QtFirebaseRemoteConfig, let other objecst can catch the QtFirebaseRemote::readyChanged signal.
=> Delay init of QtFirebaseRemoteConfig

src/platformutils.cpp, src/platformutils.h, src/qtfirebase.cpp, src/qtfirebase.h, src/qtfirebaseremoteconfig.cpp, src/qtfirebaseremoteconfig.h
- upgrade to firebase_sdk_cpp_4.1.0; [see release notes](https://firebase.google.com/support/release-notes/cpp-relnotes)
- take advantage of the new way to initialize remote_config
- check availability of Google Service before init remote_config
=> upgrade to firebase_sdk_cpp_4.1.0; 

fake/src/qtfirebase_plugin.cpp, fake/src/qtfirebasedatabase.h, src/qtfirebase_plugin.cpp
Added missing registration of auth/db classes for fake mode.
Fix compilation issue on windows
Added preprocessor defines for QtFirebaseDatabaseProvider function to skip it's compilation when no database requested in config
=> add missing auth/db registration in plugin functions

fake/src/qtfirebase_plugin.cpp, fake/src/qtfirebaseadmob.h, fake/src/qtfirebaseanalytics.h, fake/src/qtfirebaseauth.h, fake/src/qtfirebasedatabase.h, fake/src/qtfirebasemessaging.h, fake/src/qtfirebaseremoteconfig.h
Fixes compilation problems with MSVC and Windows as target as it uses different search path resolution.
When compiling for kit "Desktop Qt 5.10.1 MSVC2015 64bit" I got the following error:
fatal error C1083: Cannot open include file: "firebase/app.h": No such file or directory
If I analyzed this correctly, this is due to the way the Microsoft preprocessor handles includes in quotes, especially the following:
"2) In the directories of the currently opened include files, in the reverse order in which they were opened. The search begins in the directory of the parent include file and continues upward through the directories of any grandparent include files." (https://msdn.microsoft.com/en-us/library/36k2cdd4.aspx)
When qtfirebase_register.cpp gets compiled, it includes qtfirebase_register.h. …
=> Change includes in fake to use brackets instead of quotes

fake/src/qtfirebase.h, fake/src/qtfirebaseanalytics.h, fake/src/qtfirebasemessaging.h, fake/src/qtfirebaseservice.h, src/platformutils.cpp, src/platformutils.h, src/qtfirebase.cpp, src/qtfirebase.h, src/qtfirebaseanalytics.cpp, src/qtfirebaseanalytics.h, src/qtfirebasemessaging.cpp, src/qtfirebasemessaging.h
Currently the global references are leaking on every call to getNativeWindow() on Android.
=> Don't re-create global Android activity reference

src/qtfirebaseadmob.cpp
- Fixed QObject::killTimer: timers cannot be stopped from another thread
- Fixed another potential issues with threads
=> Make `future.OnCompletion` threadsafe

src/qtfirebaseadmob.cpp
But Qt version < 5.10 is not threadsafe.
For complete port to Qt < 5.10 need to introduce a lot of new functions, that will looks ugly and complicated.
I haven't Qt < 5.10 installed, so not tested with Qt < 5.10, but should work.
=> Restore compatibility with Qt versions < 5.10

qtfirebase_target.pri
As Android shifts towards clang, using clang will become the way to go. Due to some hardcoded reference to the gnustl version of the libraries error occurred when using clang to compile projects.
To make this more flexible, a QTFIREBASE_STL_VARIANT variable was introduced that can be set in the main app .pro file, a bit like the QTFIREBASE_DSK_PATH variable.
Setting the variable to "c++" the project will also compile with clang without linking errors (otherwise the wrong libraries are used)
=> Small change to enable clang compilation and linking

qtfirebase_target.pri, src/ios/platformutils.mm
Fixes error if xcode options
CLANG_ENABLE_OBJC_WEAK=YES
CLANG_ENABLE_OBJC_ARC=YES
is added to xcode build settings.
This options is needed to use modern Objective-C with automatic memory management.
=> Fix clang arc weak enabled

fake/src/qtfirebaseremoteconfig.h, src/qtfirebaseremoteconfig.cpp, src/qtfirebaseremoteconfig.h
Fix for #103.
Module initializer object got destructed before the post-processing code was able to process the `Future`, resulting in invalid state.
I took the liberty to remove some compiler warnings on implicit casts. Also, I removed duplicated calls on the key when copying into default byte array.
Also, I'm not sure if `__defaultsByteArrayList` needs to be a class member?
Hope this helps.
=> Remote config init

src/qtfirebaseservice.cpp
I've fixed issue when compiling QtFirebase with Analytics module.
Problem is with typing. With new platform, it seems compiler is unable to distinguish between `int` and `int64`. Somehow :S. Maybe this is a Firebase bug after all?
Related to #102.
=> Fix compilation on arm64 with analytics module

src/qtfirebaseanalytics.cpp
This generates warning and doesn't do anything anymore. I kept old QtFirebase logic for legacy reasons (in case someone has some logic tied to it :) )
=> Remove use of setMinimumSessionDuration which is deprecated

src/qtfirebaseanalytics.cpp
I couldn't find setting up session timeout anywhere on QtFirebase. It's property that decides on how long single session will persist on Firebase.  
I've added setting it up on initialisation (in `init` method) and if native part is ready in `setSessionTimeout`.
=> Add setting session timeout

src/qtfirebase.cpp, src/qtfirebase.h, src/qtfirebaseanalytics.cpp, src/qtfirebaseanalytics.h, stub/src/qtfirebaseanalytics.h
1. Fixed that ```readyChanged``` signal might not be emitted.
2. Added support for ```long long``` type.
3. Added cache to save events until the instance is ready.
4. Removed truncation of user ID because there was wrong limit of 36 (actually 256).
_At first I added all the validation rules at the Qt layer, but then I decided to delegate this work to Firebase CPP SDK only, since it also prints debug messages._
=> Analytics: Refactoring

src/qtfirebase.cpp, src/qtfirebaseremoteconfig.cpp, src/qtfirebaseremoteconfig.h, stub/src/qtfirebaseremoteconfig.h
Hello!
1. In case of Firebase CPP SDK >= 8.0.0, there was no control of futures returned from SDK code. So the correctness was not guaranteed.
2. In case of Firebase CPP SDK >= 8.0.0, no need to give up if Google Play Services is not available. They could be updating, for example, SDK defines a set of reasons and supports its API anyway. So let it decide.
3. Initial 500 ms delay has been removed from the initialization workflow: ```QTimer::singleShot(500 -> 0, ...)```.
4. Added new property ```fetching```.
5. Added new signals ```googlePlayServicesError``` and ```futuresError```.
6. Pooling future's status on timer is not an elegant and efficient solution, I used callbacks.
7. Support of Firebase CPP SDK < 8.0.0 has been kept.
8. Backward compatibility of QtFirebase API has been kept.
=> RemoteConfig: Refactoring
